##################
# Website config #
##################

name: Angry Gecko

navigation:
  - title: Home
    url: /
  - title: Who We Are
    url: /who-we-are/
  - title: How You Can Help
    url: /how-you-can-help/
  - title: Sponsors
    url: /sponsors/
  - title: Contact
    url: /contact/

footer_copyright: |
 &copy; Shaun S. 2013-2014 All rights reserved. | Website design: <a href="https://github.com/technicalguy">Shaun S</a> | Template design: <a href="http://html5up.net/">HTML5 UP</a> | <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fangrygecko.org%2F">HTML 5 Valid</a>


#######################
# Jekyll config stuff #
#######################

markdown: redcarpet
pygments: true
safe: true
timezone: Europe/London
encoding: utf-8
keep_files: ['.git']
redcarpet:
    extensions: ['smart']
# source: .
# desnination: _site