# Website config

name: Angry Gecko

navigation:
  - title: Home
    url: /
  - title: Who We Are
    url: /who-we-are/
  - title: How You Can Help
    url: /how-you-can-help/
  - title: Sponsors
    url: /sponsors/
  - title: Contact
    url: /contact/

# Jekyll config stuff

markdown: redcarpet
pygments: true
safe: true
timezone: Europe/London
encoding: utf-8
keep_files: ['.git']
redcarpet:
    extensions: ['smart']
# source: .
# desnination: _site